### ISSUE TITLE
Best Contact Information

### ISSUE THREAD

**Issue by mostman47** [Nrupesh29/CMPE-202-Team-Project#10]
I think that we need to create a worksheet and let everyone fill in best contact way/information

**Comment by iamnrupesh** [comment]
Created the Spreadsheet and shared it with all the members. Just waiting for all the members to update it with appropriate contact information.

**Comment by shettyaditi** [comment]
Updated!

**Comment by mostman47** [comment]
@ravibgupta your contact is still empty
