### ISSUE TITLE
Design the preliminary vizualization of the game

### ISSUE THREAD

**Issue by ravibgupta** [Nrupesh29/CMPE-202-Team-Project#28]
The visuals of the probable  game need to be created on a virtual canvas.

**Comment by ravibgupta** [comment]
I have uploaded the preliminary visualization of the  game. You need to take it to the next level by using the virtual sketching. Good Luck!

**Comment by shettyaditi** [comment]
Thanks.
Working on it!
Shall upload as soon as I'm done
