### ISSUE TITLE
Discuss Game Concept

### ISSUE THREAD

**Issue by iamnrupesh** [Nrupesh29/CMPE-202-Team-Project#8]
Everybody please post at least 2 games ides then we can discuss.
As well upload an image about it into github

**Comment by mostman47** [comment]
1. each player controls an actor move around by keyboard. Try catch the correct number after decode the binary number to decimal one
2. Same idea with 1, but shooter instead of move

**Comment by ravibgupta** [comment]
1. It is a MAPPY type game where there are enemies,obstructions and we need to openthe correct door that depicts the correct answer for the binary numbers equation asked as a problem.
2. It is a balloon fighter game where both players fight for survival against each other as well as fight the enemies and obstacles to eat the correct answer for the binary equation asked. it is a very interesting game.
